[E 131125 03:01:12 web:1228] Uncaught exception GET /db (127.0.0.1)
    HTTPRequest(protocol='http', host='tfbapp:8080', method='GET', uri='/db', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'tfbapp:8080', 'Accept': '*/*', 'User-Agent': 'curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3'})
    Traceback (most recent call last):
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1115, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1309, in future_complete
        self.finish()
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 749, in finish
        content_length = sum(len(part) for part in self._write_buffer)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 749, in <genexpr>
        content_length = sum(len(part) for part in self._write_buffer)
    TypeError: object of type 'NoneType' has no len()
[E 131125 03:01:12 web:1635] 500 GET /db (127.0.0.1) 47.28ms
[E 131125 03:01:12 web:1228] Uncaught exception GET /db (127.0.0.1)
    HTTPRequest(protocol='http', host='tfbapp:8080', method='GET', uri='/db', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'tfbapp:8080', 'Accept': '*/*', 'User-Agent': 'curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3'})
    Traceback (most recent call last):
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1115, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1309, in future_complete
        self.finish()
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 749, in finish
        content_length = sum(len(part) for part in self._write_buffer)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 749, in <genexpr>
        content_length = sum(len(part) for part in self._write_buffer)
    TypeError: object of type 'NoneType' has no len()
curl: (22) The requested URL returned error: 500
[E 131125 03:01:12 web:1635] 500 GET /db (127.0.0.1) 3.47ms
