[E 131215 06:24:36 web:1228] Uncaught exception GET /db (172.16.98.98)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='172.16.98.98', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131215 06:24:36 web:1635] 500 GET /db (172.16.98.98) 33.91ms
[E 131215 06:24:37 web:1228] Uncaught exception GET /db (172.16.98.98)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='172.16.98.98', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131215 06:24:37 web:1635] 500 GET /db (172.16.98.98) 1.79ms
[E 131215 06:24:38 web:1228] Uncaught exception GET /db (172.16.98.98)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='172.16.98.98', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131215 06:24:38 web:1635] 500 GET /db (172.16.98.98) 3.12ms

        
[ 120MB of this ]
        
        
[E 131215 06:28:40 web:1635] 500 GET /db?queries=20 (172.16.98.98) 24.35ms
[E 131215 06:28:40 web:1228] Uncaught exception GET /db?queries=20 (172.16.98.98)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='172.16.98.98', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 505, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 51, in get
        world = yield motor.Op(db.World.find_one, random_id)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 496, in run
        next = self.yield_point.get_result()
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/motor-0.1.2-py2.7.egg/motor/__init__.py", line 1969, in get_result
        raise error
    AutoReconnect: could not connect to 172.16.98.118:27017: error
[E 131215 06:28:40 web:1635] 500 GET /db?queries=20 (172.16.98.98) 19.36ms
[E 131215 06:28:40 web:1228] Uncaught exception GET /db?queries=20 (172.16.98.98)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='172.16.98.98', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 505, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 51, in get
        world = yield motor.Op(db.World.find_one, random_id)
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 496, in run
        next = self.yield_point.get_result()
      File "/home/tfb/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/motor-0.1.2-py2.7.egg/motor/__init__.py", line 1969, in get_result
        raise error
    AutoReconnect: could not connect to 172.16.98.118:27017: error
[E 131215 06:28:40 web:1635] 500 GET /db?queries=20 (172.16.98.98) 15.21ms
