2013-12-06 22:24:26 [11558] [INFO] Starting gunicorn 18.0
2013-12-06 22:24:26 [11558] [INFO] Listening at: http://0.0.0.0:6543 (11558)
2013-12-06 22:24:26 [11558] [INFO] Using worker: sync
2013-12-06 22:24:26 [11561] [INFO] Booting worker with pid: 11561
2013-12-06 22:24:27 [11562] [INFO] Booting worker with pid: 11562
2013-12-06 22:24:27 [11563] [INFO] Booting worker with pid: 11563
2013-12-06 22:24:27 [11564] [INFO] Booting worker with pid: 11564
2013-12-06 22:24:27 [11565] [INFO] Booting worker with pid: 11565
2013-12-06 22:24:27 [11566] [INFO] Booting worker with pid: 11566
2013-12-06 22:24:27 [11567] [INFO] Booting worker with pid: 11567
2013-12-06 22:24:27 [11568] [INFO] Booting worker with pid: 11568
2013-12-06 22:24:27 [11569] [INFO] Booting worker with pid: 11569
2013-12-06 22:24:27 [11570] [INFO] Booting worker with pid: 11570
2013-12-06 22:24:27 [11571] [INFO] Booting worker with pid: 11571
2013-12-06 22:24:27 [11572] [INFO] Booting worker with pid: 11572
2013-12-06 22:24:27 [11573] [INFO] Booting worker with pid: 11573
2013-12-06 22:24:27 [11574] [INFO] Booting worker with pid: 11574
2013-12-06 22:24:27 [11598] [INFO] Booting worker with pid: 11598
2013-12-06 22:24:27 [11603] [INFO] Booting worker with pid: 11603
2013-12-06 22:24:28 [11605] [INFO] Booting worker with pid: 11605
2013-12-06 22:24:28 [11610] [INFO] Booting worker with pid: 11610
2013-12-06 22:24:28 [11613] [INFO] Booting worker with pid: 11613
2013-12-06 22:24:28 [11614] [INFO] Booting worker with pid: 11614
2013-12-06 22:24:28 [11615] [INFO] Booting worker with pid: 11615
2013-12-06 22:24:28 [11620] [INFO] Booting worker with pid: 11620
2013-12-06 22:24:28 [11623] [INFO] Booting worker with pid: 11623
2013-12-06 22:24:28 [11626] [INFO] Booting worker with pid: 11626
2013-12-06 22:27:51 [11614] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:27:52 [11620] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:27:54 [11566] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:27:55 [11610] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:27:58 [11566] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:27:59 [11620] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:00 [11598] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:01 [11566] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:04 [11598] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:04 [11572] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:21 [11565] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:27 [11614] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:31 [11605] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:32 [11605] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:34 [11615] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:35 [11565] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:36 [11567] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:38 [11614] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:40 [11603] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:44 [11574] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:47 [11573] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:47 [11613] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:48 [11623] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:48 [11569] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:55 [11620] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:56 [11574] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:56 [11566] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:28:57 [11615] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:02 [11565] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:03 [11623] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:03 [11615] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:08 [11603] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:08 [11571] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:09 [11615] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:10 [11626] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:12 [11614] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:18 [11573] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:19 [11620] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:23 [11562] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:24 [11566] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:24 [11562] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:35 [11564] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:36 [11614] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:36 [11613] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:37 [11572] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:38 [11570] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:45 [11572] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:53 [11564] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:55 [11564] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:29:55 [11571] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:04 [11571] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:06 [11614] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:08 [11565] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:09 [11573] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:12 [11574] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:13 [11623] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:14 [11623] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:31 [11561] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:31 [11562] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:36 [11571] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:50 [11567] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:57 [11603] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:59 [11610] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:59 [11569] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:30:59 [11614] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:31:01 [11613] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:31:01 [11567] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:31:08 [11564] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:31:08 [11598] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:31:09 [11620] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:31:10 [11568] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:31:11 [11610] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:31:24 [11613] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:31:25 [11561] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:31:25 [11613] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:31:26 [11603] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:31:44 [11620] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:34:17 [11610] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:34:19 [11571] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:34:21 [11626] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:34:24 [11561] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:34:26 [11569] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:01 [11565] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:03 [11573] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:17 [11561] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:19 [11614] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:23 [11563] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:23 [11623] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:23 [11570] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:24 [11574] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:24 [11614] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:25 [11569] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:25 [11564] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:32 [11569] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:34 [11563] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:35 [11614] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:36 [11598] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:35:37 [11567] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:36:08 [11563] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-06 22:37:37 [11558] [INFO] Handling signal: term
2013-12-06 22:37:37 [11605] [INFO] Worker exiting (pid: 11605)
2013-12-06 22:37:37 [11570] [INFO] Worker exiting (pid: 11570)
2013-12-06 22:37:37 [11620] [INFO] Worker exiting (pid: 11620)
2013-12-06 22:37:37 [11565] [INFO] Worker exiting (pid: 11565)
2013-12-06 22:37:37 [11626] [INFO] Worker exiting (pid: 11626)
2013-12-06 22:37:37 [11598] [INFO] Worker exiting (pid: 11598)
2013-12-06 22:37:37 [11562] [INFO] Worker exiting (pid: 11562)
2013-12-06 22:37:37 [11563] [INFO] Worker exiting (pid: 11563)
2013-12-06 22:37:37 [11567] [INFO] Worker exiting (pid: 11567)
2013-12-06 22:37:37 [11574] [INFO] Worker exiting (pid: 11574)
2013-12-06 22:37:37 [11613] [INFO] Worker exiting (pid: 11613)
2013-12-06 22:37:37 [11614] [INFO] Worker exiting (pid: 11614)
2013-12-06 22:37:37 [11571] [INFO] Worker exiting (pid: 11571)
2013-12-06 22:37:37 [11623] [INFO] Worker exiting (pid: 11623)
2013-12-06 22:37:37 [11561] [INFO] Worker exiting (pid: 11561)
2013-12-06 22:37:37 [11610] [INFO] Worker exiting (pid: 11610)
2013-12-06 22:37:37 [11558] [INFO] Shutting down: Master
