[E 131214 16:27:30 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:27:30 web:1635] 500 GET /db (10.232.38.44) 213.07ms
[E 131214 16:27:35 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:27:35 web:1635] 500 GET /db (10.232.38.44) 68.14ms
[E 131214 16:27:39 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:27:39 web:1635] 500 GET /db (10.232.38.44) 36.72ms
[E 131214 16:27:39 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:27:39 web:1635] 500 GET /db (10.232.38.44) 32.59ms
[E 131214 16:27:58 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:27:58 web:1635] 500 GET /db (10.232.38.44) 3.53ms
[E 131214 16:27:58 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:27:58 web:1635] 500 GET /db (10.232.38.44) 2.95ms
[E 131214 16:27:59 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:27:59 web:1635] 500 GET /db (10.232.38.44) 3.99ms
[E 131214 16:28:00 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:00 web:1635] 500 GET /db (10.232.38.44) 2.87ms
[E 131214 16:28:04 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:04 web:1635] 500 GET /db (10.232.38.44) 4.19ms
[E 131214 16:28:05 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:05 web:1635] 500 GET /db (10.232.38.44) 4.13ms
[E 131214 16:28:05 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:05 web:1635] 500 GET /db (10.232.38.44) 4.31ms
[E 131214 16:28:08 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:08 web:1635] 500 GET /db (10.232.38.44) 3.88ms
[E 131214 16:28:08 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:08 web:1635] 500 GET /db (10.232.38.44) 4.28ms
[E 131214 16:28:08 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:08 web:1635] 500 GET /db (10.232.38.44) 5.68ms
[E 131214 16:28:09 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:09 web:1635] 500 GET /db (10.232.38.44) 3.26ms
[E 131214 16:28:11 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:11 web:1635] 500 GET /db (10.232.38.44) 3.58ms
[E 131214 16:28:12 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:12 web:1635] 500 GET /db (10.232.38.44) 6.96ms
[E 131214 16:28:14 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:14 web:1635] 500 GET /db (10.232.38.44) 3.08ms
[E 131214 16:28:14 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:14 web:1635] 500 GET /db (10.232.38.44) 3.11ms
[E 131214 16:28:15 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:15 web:1635] 500 GET /db (10.232.38.44) 3.05ms
[E 131214 16:28:16 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:16 web:1635] 500 GET /db (10.232.38.44) 3.35ms
[E 131214 16:28:21 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:21 web:1635] 500 GET /db (10.232.38.44) 5.59ms
[E 131214 16:28:26 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:26 web:1635] 500 GET /db (10.232.38.44) 6.82ms
[E 131214 16:28:27 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:27 web:1635] 500 GET /db (10.232.38.44) 9.75ms
[E 131214 16:28:30 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:30 web:1635] 500 GET /db (10.232.38.44) 4.55ms
[E 131214 16:28:30 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:30 web:1635] 500 GET /db (10.232.38.44) 10.20ms
[E 131214 16:28:31 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:31 web:1635] 500 GET /db (10.232.38.44) 9.76ms
[E 131214 16:28:34 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:34 web:1635] 500 GET /db (10.232.38.44) 3.77ms
[E 131214 16:28:35 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:35 web:1635] 500 GET /db (10.232.38.44) 10.98ms
[E 131214 16:28:35 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:35 web:1635] 500 GET /db (10.232.38.44) 9.82ms
[E 131214 16:28:38 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:38 web:1635] 500 GET /db (10.232.38.44) 8.79ms
[E 131214 16:28:39 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:39 web:1635] 500 GET /db (10.232.38.44) 13.23ms
[E 131214 16:28:39 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:39 web:1635] 500 GET /db (10.232.38.44) 11.07ms
[E 131214 16:28:40 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:40 web:1635] 500 GET /db (10.232.38.44) 9.97ms
[E 131214 16:28:41 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:41 web:1635] 500 GET /db (10.232.38.44) 11.98ms
[E 131214 16:28:42 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:42 web:1635] 500 GET /db (10.232.38.44) 7.45ms
[E 131214 16:28:44 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:44 web:1635] 500 GET /db (10.232.38.44) 13.13ms
[E 131214 16:28:45 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:45 web:1635] 500 GET /db (10.232.38.44) 8.22ms
[E 131214 16:28:46 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:46 web:1635] 500 GET /db (10.232.38.44) 10.23ms
[E 131214 16:28:47 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:47 web:1635] 500 GET /db (10.232.38.44) 10.76ms
[E 131214 16:28:50 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:50 web:1635] 500 GET /db (10.232.38.44) 11.61ms
[E 131214 16:28:52 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:52 web:1635] 500 GET /db (10.232.38.44) 11.46ms
[E 131214 16:28:58 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:58 web:1635] 500 GET /db (10.232.38.44) 17.91ms
[E 131214 16:28:58 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:28:58 web:1635] 500 GET /db (10.232.38.44) 23.33ms
[E 131214 16:29:00 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:00 web:1635] 500 GET /db (10.232.38.44) 29.38ms
[E 131214 16:29:02 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:02 web:1635] 500 GET /db (10.232.38.44) 20.57ms
[E 131214 16:29:06 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:06 web:1635] 500 GET /db (10.232.38.44) 15.74ms
[E 131214 16:29:12 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:12 web:1635] 500 GET /db (10.232.38.44) 24.48ms
[E 131214 16:29:13 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:13 web:1635] 500 GET /db (10.232.38.44) 36.43ms
[E 131214 16:29:14 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:14 web:1635] 500 GET /db (10.232.38.44) 54.44ms
[E 131214 16:29:14 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:14 web:1635] 500 GET /db (10.232.38.44) 49.61ms
[E 131214 16:29:19 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:19 web:1635] 500 GET /db (10.232.38.44) 36.73ms
[E 131214 16:29:21 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:21 web:1635] 500 GET /db (10.232.38.44) 71.30ms
[E 131214 16:29:23 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:23 web:1635] 500 GET /db (10.232.38.44) 36.84ms
[E 131214 16:29:24 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:24 web:1635] 500 GET /db (10.232.38.44) 36.53ms
[E 131214 16:29:25 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:25 web:1635] 500 GET /db (10.232.38.44) 46.02ms
[E 131214 16:29:26 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:26 web:1635] 500 GET /db (10.232.38.44) 30.21ms
[E 131214 16:29:27 web:1228] Uncaught exception GET /db (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:27 web:1635] 500 GET /db (10.232.38.44) 47.17ms
[E 131214 16:29:32 web:1228] Uncaught exception GET /db?queries=2 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:32 web:1635] 500 GET /db?queries=2 (10.232.38.44) 5.57ms
[E 131214 16:29:32 web:1228] Uncaught exception GET /db?queries=2 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:32 web:1635] 500 GET /db?queries=2 (10.232.38.44) 3.48ms
[E 131214 16:29:33 web:1228] Uncaught exception GET /db?queries=2 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:33 web:1635] 500 GET /db?queries=2 (10.232.38.44) 3.68ms
[E 131214 16:29:35 web:1228] Uncaught exception GET /db?queries=2 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:35 web:1635] 500 GET /db?queries=2 (10.232.38.44) 3.38ms
[E 131214 16:29:41 web:1228] Uncaught exception GET /db?queries=2 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:41 web:1635] 500 GET /db?queries=2 (10.232.38.44) 45.49ms
[E 131214 16:29:43 web:1228] Uncaught exception GET /db?queries=2 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:43 web:1635] 500 GET /db?queries=2 (10.232.38.44) 48.11ms
[E 131214 16:29:46 web:1228] Uncaught exception GET /db?queries=2 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:46 web:1635] 500 GET /db?queries=2 (10.232.38.44) 133.18ms
[E 131214 16:29:52 web:1228] Uncaught exception GET /db?queries=2 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:52 web:1635] 500 GET /db?queries=2 (10.232.38.44) 161.27ms
[E 131214 16:29:54 web:1228] Uncaught exception GET /db?queries=2 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:29:54 web:1635] 500 GET /db?queries=2 (10.232.38.44) 44.17ms
[E 131214 16:30:01 web:1228] Uncaught exception GET /db?queries=1 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:01 web:1635] 500 GET /db?queries=1 (10.232.38.44) 59.28ms
[E 131214 16:30:01 web:1228] Uncaught exception GET /db?queries=1 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:01 web:1635] 500 GET /db?queries=1 (10.232.38.44) 59.07ms
[E 131214 16:30:02 web:1228] Uncaught exception GET /db?queries=1 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:02 web:1635] 500 GET /db?queries=1 (10.232.38.44) 142.95ms
[E 131214 16:30:03 web:1228] Uncaught exception GET /db?queries=1 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:03 web:1635] 500 GET /db?queries=1 (10.232.38.44) 61.71ms
[E 131214 16:30:05 web:1228] Uncaught exception GET /db?queries=1 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:05 web:1635] 500 GET /db?queries=1 (10.232.38.44) 26.73ms
[E 131214 16:30:11 web:1228] Uncaught exception GET /db?queries=1 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:11 web:1635] 500 GET /db?queries=1 (10.232.38.44) 34.65ms
[E 131214 16:30:12 web:1228] Uncaught exception GET /db?queries=1 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:12 web:1635] 500 GET /db?queries=1 (10.232.38.44) 38.71ms
[E 131214 16:30:14 web:1228] Uncaught exception GET /db?queries=1 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:14 web:1635] 500 GET /db?queries=1 (10.232.38.44) 55.17ms
[E 131214 16:30:17 web:1228] Uncaught exception GET /db?queries=5 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:17 web:1635] 500 GET /db?queries=5 (10.232.38.44) 41.36ms
[E 131214 16:30:19 web:1228] Uncaught exception GET /db?queries=5 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:19 web:1635] 500 GET /db?queries=5 (10.232.38.44) 178.31ms
[E 131214 16:30:21 web:1228] Uncaught exception GET /db?queries=5 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:21 web:1635] 500 GET /db?queries=5 (10.232.38.44) 66.52ms
[E 131214 16:30:23 web:1228] Uncaught exception GET /db?queries=5 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:24 web:1635] 500 GET /db?queries=5 (10.232.38.44) 51.56ms
[E 131214 16:30:25 web:1228] Uncaught exception GET /db?queries=5 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:25 web:1635] 500 GET /db?queries=5 (10.232.38.44) 67.45ms
[E 131214 16:30:27 web:1228] Uncaught exception GET /db?queries=5 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:27 web:1635] 500 GET /db?queries=5 (10.232.38.44) 231.56ms
[E 131214 16:30:29 web:1228] Uncaught exception GET /db?queries=5 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:29 web:1635] 500 GET /db?queries=5 (10.232.38.44) 18.44ms
[E 131214 16:30:30 web:1228] Uncaught exception GET /db?queries=5 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:30 web:1635] 500 GET /db?queries=5 (10.232.38.44) 40.02ms
[E 131214 16:30:30 web:1228] Uncaught exception GET /db?queries=5 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:30 web:1635] 500 GET /db?queries=5 (10.232.38.44) 40.13ms
[E 131214 16:30:32 web:1228] Uncaught exception GET /db?queries=5 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:32 web:1635] 500 GET /db?queries=5 (10.232.38.44) 32.42ms
[E 131214 16:30:34 web:1228] Uncaught exception GET /db?queries=10 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:34 web:1635] 500 GET /db?queries=10 (10.232.38.44) 120.00ms
[E 131214 16:30:34 web:1228] Uncaught exception GET /db?queries=10 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:34 web:1635] 500 GET /db?queries=10 (10.232.38.44) 38.91ms
[E 131214 16:30:36 web:1228] Uncaught exception GET /db?queries=10 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:36 web:1635] 500 GET /db?queries=10 (10.232.38.44) 108.71ms
[E 131214 16:30:36 web:1228] Uncaught exception GET /db?queries=10 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:36 web:1635] 500 GET /db?queries=10 (10.232.38.44) 19.84ms
[E 131214 16:30:36 web:1228] Uncaught exception GET /db?queries=10 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:36 web:1635] 500 GET /db?queries=10 (10.232.38.44) 42.28ms
[E 131214 16:30:37 web:1228] Uncaught exception GET /db?queries=10 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:37 web:1635] 500 GET /db?queries=10 (10.232.38.44) 181.07ms
[E 131214 16:30:40 web:1228] Uncaught exception GET /db?queries=10 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:40 web:1635] 500 GET /db?queries=10 (10.232.38.44) 123.10ms
[E 131214 16:30:45 web:1228] Uncaught exception GET /db?queries=10 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:45 web:1635] 500 GET /db?queries=10 (10.232.38.44) 66.24ms
[E 131214 16:30:46 web:1228] Uncaught exception GET /db?queries=10 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:46 web:1635] 500 GET /db?queries=10 (10.232.38.44) 459.89ms
[E 131214 16:30:48 web:1228] Uncaught exception GET /db?queries=10 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:48 web:1635] 500 GET /db?queries=10 (10.232.38.44) 43.02ms
[E 131214 16:30:49 web:1228] Uncaught exception GET /db?queries=10 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:49 web:1635] 500 GET /db?queries=10 (10.232.38.44) 56.15ms
[E 131214 16:30:52 web:1228] Uncaught exception GET /db?queries=15 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:52 web:1635] 500 GET /db?queries=15 (10.232.38.44) 729.26ms
[E 131214 16:30:53 web:1228] Uncaught exception GET /db?queries=15 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:53 web:1635] 500 GET /db?queries=15 (10.232.38.44) 25.33ms
[E 131214 16:30:55 web:1228] Uncaught exception GET /db?queries=15 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:55 web:1635] 500 GET /db?queries=15 (10.232.38.44) 465.36ms
[E 131214 16:30:55 web:1228] Uncaught exception GET /db?queries=15 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:55 web:1635] 500 GET /db?queries=15 (10.232.38.44) 172.06ms
[E 131214 16:30:57 web:1228] Uncaught exception GET /db?queries=15 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:57 web:1635] 500 GET /db?queries=15 (10.232.38.44) 479.23ms
[E 131214 16:30:58 web:1228] Uncaught exception GET /db?queries=15 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:58 web:1635] 500 GET /db?queries=15 (10.232.38.44) 133.03ms
[E 131214 16:30:59 web:1228] Uncaught exception GET /db?queries=15 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:30:59 web:1635] 500 GET /db?queries=15 (10.232.38.44) 22.85ms
[E 131214 16:31:00 web:1228] Uncaught exception GET /db?queries=15 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:00 web:1635] 500 GET /db?queries=15 (10.232.38.44) 150.85ms
[E 131214 16:31:08 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:08 web:1635] 500 GET /db?queries=20 (10.232.38.44) 107.41ms
[E 131214 16:31:09 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:09 web:1635] 500 GET /db?queries=20 (10.232.38.44) 20.17ms
[E 131214 16:31:10 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:10 web:1635] 500 GET /db?queries=20 (10.232.38.44) 747.36ms
[E 131214 16:31:11 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:11 web:1635] 500 GET /db?queries=20 (10.232.38.44) 14.24ms
[E 131214 16:31:12 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:12 web:1635] 500 GET /db?queries=20 (10.232.38.44) 87.29ms
[E 131214 16:31:12 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:12 web:1635] 500 GET /db?queries=20 (10.232.38.44) 183.52ms
[E 131214 16:31:13 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:13 web:1635] 500 GET /db?queries=20 (10.232.38.44) 73.06ms
[E 131214 16:31:13 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:13 web:1635] 500 GET /db?queries=20 (10.232.38.44) 251.62ms
[E 131214 16:31:18 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:18 web:1635] 500 GET /db?queries=20 (10.232.38.44) 229.82ms
[E 131214 16:31:18 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:18 web:1635] 500 GET /db?queries=20 (10.232.38.44) 284.92ms
[E 131214 16:31:18 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:18 web:1635] 500 GET /db?queries=20 (10.232.38.44) 23.01ms
[E 131214 16:31:20 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:20 web:1635] 500 GET /db?queries=20 (10.232.38.44) 16.78ms
[E 131214 16:31:22 web:1228] Uncaught exception GET /db?queries=20 (10.232.38.44)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.232.38.44', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131214 16:31:22 web:1635] 500 GET /db?queries=20 (10.232.38.44) 89.86ms
