ERROR:app:Exception on /json [GET]
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/FrameworkBenchmarks/flask/app.py", line 64, in hello
    return jsonify(message='Hello, World!')
NameError: global name 'jsonify' is not defined
ERROR:tornado.access:500 GET /json (10.254.7.165) 113.85ms
ERROR:app:Exception on /json [GET]
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/FrameworkBenchmarks/flask/app.py", line 64, in hello
    return jsonify(message='Hello, World!')
NameError: global name 'jsonify' is not defined
curl: (22) The requested URL returned error: 500
ERROR:tornado.access:500 GET /json (10.254.7.165) 2.21ms
ERROR:tornado.application:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/iostream.py", line 341, in wrapper
    callback(*args)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
ERROR:tornado.application:Exception in callback <_functools.partial object at 0x000000000ebc9d70>
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/ioloop.py", line 458, in _run_callback
    callback()
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/lib_pypy/_functools.py", line 22, in __call__
    return self.func(*(self.args + fargs), **fkeywords)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/iostream.py", line 341, in wrapper
    callback(*args)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
ERROR:tornado.application:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/iostream.py", line 341, in wrapper
    callback(*args)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
ERROR:tornado.application:Exception in callback <_functools.partial object at 0x000000000ebafec0>
Traceback (most recent call last):
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/ioloop.py", line 458, in _run_callback
    callback()
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/lib_pypy/_functools.py", line 22, in __call__
    return self.func(*(self.args + fargs), **fkeywords)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/iostream.py", line 341, in wrapper
    callback(*args)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
debug: OperationError:
debug:  operror-type: SystemExit
debug:  operror-value: 0
debug: OperationError:
debug:  operror-type: SystemExit
debug:  operror-value: 0
