2013-12-14 23:50:28 [7724] [INFO] Starting gunicorn 18.0
2013-12-14 23:50:28 [7724] [INFO] Listening at: http://0.0.0.0:6543 (7724)
2013-12-14 23:50:28 [7724] [INFO] Using worker: sync
2013-12-14 23:50:28 [7727] [INFO] Booting worker with pid: 7727
2013-12-14 23:50:28 [7728] [INFO] Booting worker with pid: 7728
2013-12-14 23:50:28 [7729] [INFO] Booting worker with pid: 7729
2013-12-14 23:50:28 [7730] [INFO] Booting worker with pid: 7730
2013-12-14 23:50:28 [7731] [INFO] Booting worker with pid: 7731
2013-12-14 23:50:28 [7732] [INFO] Booting worker with pid: 7732
2013-12-14 23:50:28 [7733] [INFO] Booting worker with pid: 7733
2013-12-14 23:50:28 [7734] [INFO] Booting worker with pid: 7734
2013-12-14 23:50:28 [7735] [INFO] Booting worker with pid: 7735
2013-12-14 23:50:28 [7736] [INFO] Booting worker with pid: 7736
2013-12-14 23:50:28 [7737] [INFO] Booting worker with pid: 7737
2013-12-14 23:50:28 [7738] [INFO] Booting worker with pid: 7738
2013-12-14 23:50:28 [7739] [INFO] Booting worker with pid: 7739
2013-12-14 23:50:28 [7740] [INFO] Booting worker with pid: 7740
2013-12-14 23:50:28 [7741] [INFO] Booting worker with pid: 7741
2013-12-14 23:50:29 [7742] [INFO] Booting worker with pid: 7742
2013-12-14 23:50:29 [7743] [INFO] Booting worker with pid: 7743
2013-12-14 23:50:29 [7774] [INFO] Booting worker with pid: 7774
2013-12-14 23:50:29 [7779] [INFO] Booting worker with pid: 7779
2013-12-14 23:50:29 [7782] [INFO] Booting worker with pid: 7782
2013-12-14 23:50:29 [7783] [INFO] Booting worker with pid: 7783
2013-12-14 23:50:29 [7786] [INFO] Booting worker with pid: 7786
2013-12-14 23:50:29 [7791] [INFO] Booting worker with pid: 7791
2013-12-14 23:50:29 [7792] [INFO] Booting worker with pid: 7792
2013-12-14 23:53:42 [7737] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:53:51 [7728] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:53:56 [7774] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:53:57 [7737] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:54:02 [7782] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:54:28 [7738] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:54:35 [7727] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:54:37 [7740] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:54:41 [7792] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:54:45 [7732] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:54:47 [7741] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:54:47 [7742] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:54:47 [7735] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:54:48 [7737] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:54:55 [7728] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:03 [7783] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:04 [7786] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:10 [7737] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:11 [7792] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:11 [7732] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:12 [7736] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:20 [7743] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:20 [7786] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:21 [7732] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:21 [7783] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:27 [7783] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:28 [7774] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:28 [7739] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:29 [7734] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:29 [7737] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:30 [7783] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:33 [7735] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:33 [7741] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:36 [7779] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:38 [7741] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:38 [7729] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:39 [7736] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:55:46 [7741] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 25, in test_2
    result = DBSession.query(World).filter(World.id == num).one()
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:56:07 [7735] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:56:07 [7738] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:56:14 [7741] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:56:16 [7735] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:56:17 [7742] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:56:18 [7740] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:56:33 [7733] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:56:53 [7786] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:09 [7783] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:09 [7742] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:09 [7734] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:10 [7786] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:10 [7779] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:11 [7779] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:26 [7786] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:29 [7736] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:44 [7731] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:44 [7733] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:45 [7739] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:46 [7732] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:46 [7727] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-14 23:57:47 [7742] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in test_3
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 46, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:00:20 [7743] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:01:09 [7729] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:01:11 [7729] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:01:12 [7783] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:01:13 [7733] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:01:16 [7786] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:01:22 [7737] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:01:22 [7731] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:01:37 [7779] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:01:38 [7792] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:01:39 [7736] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:01:39 [7731] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/gunicorn-18.0-py3.3.egg/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in test_5
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/pyramid/frameworkbenchmarks/views.py", line 80, in <listcomp>
    for num in [randint(1, 10001) for _ in range(1, queries + 1)]
  File "/home/tfb/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/SQLAlchemy-0.9.0b1-py3.3-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2309, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2013-12-15 00:03:40 [7724] [INFO] Handling signal: term
2013-12-15 00:03:40 [7728] [INFO] Worker exiting (pid: 7728)
2013-12-15 00:03:40 [7736] [INFO] Worker exiting (pid: 7736)
2013-12-15 00:03:40 [7792] [INFO] Worker exiting (pid: 7792)
2013-12-15 00:03:40 [7741] [INFO] Worker exiting (pid: 7741)
2013-12-15 00:03:40 [7743] [INFO] Worker exiting (pid: 7743)
2013-12-15 00:03:40 [7742] [INFO] Worker exiting (pid: 7742)
2013-12-15 00:03:40 [7738] [INFO] Worker exiting (pid: 7738)
2013-12-15 00:03:40 [7740] [INFO] Worker exiting (pid: 7740)
2013-12-15 00:03:40 [7733] [INFO] Worker exiting (pid: 7733)
2013-12-15 00:03:40 [7727] [INFO] Worker exiting (pid: 7727)
2013-12-15 00:03:40 [7782] [INFO] Worker exiting (pid: 7782)
2013-12-15 00:03:40 [7729] [INFO] Worker exiting (pid: 7729)
2013-12-15 00:03:40 [7737] [INFO] Worker exiting (pid: 7737)
2013-12-15 00:03:40 [7724] [INFO] Shutting down: Master
