Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/bin/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==18.0', 'console_scripts', 'gunicorn')()
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/gunicorn-18.0-py2.7.egg/gunicorn/app/wsgiapp.py", line 71, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/gunicorn-18.0-py2.7.egg/gunicorn/app/base.py", line 143, in run
    Arbiter(self).run()
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 203, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 298, in halt
    self.stop()
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 341, in stop
    self.reap_workers()
  File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/gunicorn-18.0-py2.7.egg/gunicorn/arbiter.py", line 452, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
HaltServer: <HaltServer 'Worker failed to boot.' 3>
curl: (7) couldn't connect to host
curl: (7) couldn't connect to host
curl: (7) couldn't connect to host
curl: (7) couldn't connect to host
curl: (7) couldn't connect to host
curl: (7) couldn't connect to host
