[E 131210 14:38:06 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:06 web:1635] 500 GET /db (10.253.6.188) 7.24ms
[E 131210 14:38:21 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:21 web:1635] 500 GET /db (10.253.6.188) 48.53ms
[E 131210 14:38:22 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:22 web:1635] 500 GET /db (10.253.6.188) 51.85ms
[E 131210 14:38:35 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:35 web:1635] 500 GET /db (10.253.6.188) 5.06ms
[E 131210 14:38:38 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:38 web:1635] 500 GET /db (10.253.6.188) 3.10ms
[E 131210 14:38:39 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:39 web:1635] 500 GET /db (10.253.6.188) 2.36ms
[E 131210 14:38:39 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:39 web:1635] 500 GET /db (10.253.6.188) 4.01ms
[E 131210 14:38:43 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:43 web:1635] 500 GET /db (10.253.6.188) 2.53ms
[E 131210 14:38:43 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:43 web:1635] 500 GET /db (10.253.6.188) 3.58ms
[E 131210 14:38:44 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:44 web:1635] 500 GET /db (10.253.6.188) 3.59ms
[E 131210 14:38:44 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:44 web:1635] 500 GET /db (10.253.6.188) 2.51ms
[E 131210 14:38:51 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:51 web:1635] 500 GET /db (10.253.6.188) 3.56ms
[E 131210 14:38:52 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:52 web:1635] 500 GET /db (10.253.6.188) 5.18ms
[E 131210 14:38:54 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:54 web:1635] 500 GET /db (10.253.6.188) 3.48ms
[E 131210 14:38:54 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:54 web:1635] 500 GET /db (10.253.6.188) 4.25ms
[E 131210 14:38:55 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:55 web:1635] 500 GET /db (10.253.6.188) 5.04ms
[E 131210 14:38:56 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:56 web:1635] 500 GET /db (10.253.6.188) 3.96ms
[E 131210 14:38:58 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:38:58 web:1635] 500 GET /db (10.253.6.188) 3.61ms
[E 131210 14:39:01 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:01 web:1635] 500 GET /db (10.253.6.188) 3.36ms
[E 131210 14:39:02 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:02 web:1635] 500 GET /db (10.253.6.188) 4.66ms
[E 131210 14:39:02 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:02 web:1635] 500 GET /db (10.253.6.188) 3.15ms
[E 131210 14:39:09 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:09 web:1635] 500 GET /db (10.253.6.188) 6.04ms
[E 131210 14:39:09 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:09 web:1635] 500 GET /db (10.253.6.188) 7.57ms
[E 131210 14:39:12 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:12 web:1635] 500 GET /db (10.253.6.188) 8.09ms
[E 131210 14:39:13 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:13 web:1635] 500 GET /db (10.253.6.188) 5.15ms
[E 131210 14:39:18 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:18 web:1635] 500 GET /db (10.253.6.188) 5.86ms
[E 131210 14:39:18 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:18 web:1635] 500 GET /db (10.253.6.188) 5.15ms
[E 131210 14:39:20 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:20 web:1635] 500 GET /db (10.253.6.188) 7.84ms
[E 131210 14:39:29 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:29 web:1635] 500 GET /db (10.253.6.188) 7.81ms
[E 131210 14:39:30 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:30 web:1635] 500 GET /db (10.253.6.188) 10.85ms
[E 131210 14:39:30 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:30 web:1635] 500 GET /db (10.253.6.188) 7.73ms
[E 131210 14:39:32 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:32 web:1635] 500 GET /db (10.253.6.188) 11.14ms
[E 131210 14:39:32 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:32 web:1635] 500 GET /db (10.253.6.188) 8.79ms
[E 131210 14:39:43 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:43 web:1635] 500 GET /db (10.253.6.188) 19.38ms
[E 131210 14:39:49 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:49 web:1635] 500 GET /db (10.253.6.188) 22.15ms
[E 131210 14:39:54 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:39:54 web:1635] 500 GET /db (10.253.6.188) 94.33ms
[E 131210 14:40:01 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:01 web:1635] 500 GET /db (10.253.6.188) 110.12ms
[E 131210 14:40:03 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:03 web:1635] 500 GET /db (10.253.6.188) 41.00ms
[E 131210 14:40:04 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:04 web:1635] 500 GET /db (10.253.6.188) 115.91ms
[E 131210 14:40:10 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:10 web:1635] 500 GET /db (10.253.6.188) 37.08ms
[E 131210 14:40:11 web:1228] Uncaught exception GET /db (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 45, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:11 web:1635] 500 GET /db (10.253.6.188) 59.61ms
[E 131210 14:40:18 web:1228] Uncaught exception GET /db?queries=2 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:18 web:1635] 500 GET /db?queries=2 (10.253.6.188) 3.69ms
[E 131210 14:40:33 web:1228] Uncaught exception GET /db?queries=2 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:33 web:1635] 500 GET /db?queries=2 (10.253.6.188) 44.51ms
[E 131210 14:40:34 web:1228] Uncaught exception GET /db?queries=2 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:34 web:1635] 500 GET /db?queries=2 (10.253.6.188) 45.25ms
[E 131210 14:40:38 web:1228] Uncaught exception GET /db?queries=2 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:38 web:1635] 500 GET /db?queries=2 (10.253.6.188) 82.14ms
[E 131210 14:40:39 web:1228] Uncaught exception GET /db?queries=2 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=2', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:39 web:1635] 500 GET /db?queries=2 (10.253.6.188) 40.60ms
[E 131210 14:40:46 web:1228] Uncaught exception GET /db?queries=1 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:46 web:1635] 500 GET /db?queries=1 (10.253.6.188) 48.63ms
[E 131210 14:40:47 web:1228] Uncaught exception GET /db?queries=1 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:47 web:1635] 500 GET /db?queries=1 (10.253.6.188) 44.51ms
[E 131210 14:40:51 web:1228] Uncaught exception GET /db?queries=1 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:51 web:1635] 500 GET /db?queries=1 (10.253.6.188) 39.26ms
[E 131210 14:40:53 web:1228] Uncaught exception GET /db?queries=1 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:53 web:1635] 500 GET /db?queries=1 (10.253.6.188) 50.22ms
[E 131210 14:40:55 web:1228] Uncaught exception GET /db?queries=1 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=1', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:40:55 web:1635] 500 GET /db?queries=1 (10.253.6.188) 41.65ms
[E 131210 14:41:03 web:1228] Uncaught exception GET /db?queries=5 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:03 web:1635] 500 GET /db?queries=5 (10.253.6.188) 306.05ms
[E 131210 14:41:06 web:1228] Uncaught exception GET /db?queries=5 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:06 web:1635] 500 GET /db?queries=5 (10.253.6.188) 240.29ms
[E 131210 14:41:07 web:1228] Uncaught exception GET /db?queries=5 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:07 web:1635] 500 GET /db?queries=5 (10.253.6.188) 48.50ms
[E 131210 14:41:08 web:1228] Uncaught exception GET /db?queries=5 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:08 web:1635] 500 GET /db?queries=5 (10.253.6.188) 206.87ms
[E 131210 14:41:08 web:1228] Uncaught exception GET /db?queries=5 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:08 web:1635] 500 GET /db?queries=5 (10.253.6.188) 110.23ms
[E 131210 14:41:08 web:1228] Uncaught exception GET /db?queries=5 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:08 web:1635] 500 GET /db?queries=5 (10.253.6.188) 19.05ms
[E 131210 14:41:09 web:1228] Uncaught exception GET /db?queries=5 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:09 web:1635] 500 GET /db?queries=5 (10.253.6.188) 97.17ms
[E 131210 14:41:13 web:1228] Uncaught exception GET /db?queries=5 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:13 web:1635] 500 GET /db?queries=5 (10.253.6.188) 112.82ms
[E 131210 14:41:14 web:1228] Uncaught exception GET /db?queries=5 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:14 web:1635] 500 GET /db?queries=5 (10.253.6.188) 192.32ms
[E 131210 14:41:16 web:1228] Uncaught exception GET /db?queries=5 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:16 web:1635] 500 GET /db?queries=5 (10.253.6.188) 99.35ms
[E 131210 14:41:16 web:1228] Uncaught exception GET /db?queries=5 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=5', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:16 web:1635] 500 GET /db?queries=5 (10.253.6.188) 71.94ms
[E 131210 14:41:20 web:1228] Uncaught exception GET /db?queries=10 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:20 web:1635] 500 GET /db?queries=10 (10.253.6.188) 365.39ms
[E 131210 14:41:22 web:1228] Uncaught exception GET /db?queries=10 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:22 web:1635] 500 GET /db?queries=10 (10.253.6.188) 535.40ms
[E 131210 14:41:23 web:1228] Uncaught exception GET /db?queries=10 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:23 web:1635] 500 GET /db?queries=10 (10.253.6.188) 368.75ms
[E 131210 14:41:23 web:1228] Uncaught exception GET /db?queries=10 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:23 web:1635] 500 GET /db?queries=10 (10.253.6.188) 116.39ms
[E 131210 14:41:25 web:1228] Uncaught exception GET /db?queries=10 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:25 web:1635] 500 GET /db?queries=10 (10.253.6.188) 26.52ms
[E 131210 14:41:27 web:1228] Uncaught exception GET /db?queries=10 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:27 web:1635] 500 GET /db?queries=10 (10.253.6.188) 525.72ms
[E 131210 14:41:28 web:1228] Uncaught exception GET /db?queries=10 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:28 web:1635] 500 GET /db?queries=10 (10.253.6.188) 488.82ms
[E 131210 14:41:28 web:1228] Uncaught exception GET /db?queries=10 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:28 web:1635] 500 GET /db?queries=10 (10.253.6.188) 339.72ms
[E 131210 14:41:31 web:1228] Uncaught exception GET /db?queries=10 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:31 web:1635] 500 GET /db?queries=10 (10.253.6.188) 100.56ms
[E 131210 14:41:32 web:1228] Uncaught exception GET /db?queries=10 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=10', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:32 web:1635] 500 GET /db?queries=10 (10.253.6.188) 686.55ms
[E 131210 14:41:41 web:1228] Uncaught exception GET /db?queries=15 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:41 web:1635] 500 GET /db?queries=15 (10.253.6.188) 333.73ms
[E 131210 14:41:48 web:1228] Uncaught exception GET /db?queries=15 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:48 web:1635] 500 GET /db?queries=15 (10.253.6.188) 214.07ms
[E 131210 14:41:49 web:1228] Uncaught exception GET /db?queries=15 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:49 web:1635] 500 GET /db?queries=15 (10.253.6.188) 319.62ms
[E 131210 14:41:50 web:1228] Uncaught exception GET /db?queries=15 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:50 web:1635] 500 GET /db?queries=15 (10.253.6.188) 756.25ms
[E 131210 14:41:50 web:1228] Uncaught exception GET /db?queries=15 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:50 web:1635] 500 GET /db?queries=15 (10.253.6.188) 212.05ms
[E 131210 14:41:50 web:1228] Uncaught exception GET /db?queries=15 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:50 web:1635] 500 GET /db?queries=15 (10.253.6.188) 244.87ms
[E 131210 14:41:51 web:1228] Uncaught exception GET /db?queries=15 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:51 web:1635] 500 GET /db?queries=15 (10.253.6.188) 320.19ms
[E 131210 14:41:51 web:1228] Uncaught exception GET /db?queries=15 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=15', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:51 web:1635] 500 GET /db?queries=15 (10.253.6.188) 379.75ms
[E 131210 14:41:55 web:1228] Uncaught exception GET /db?queries=20 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:55 web:1635] 500 GET /db?queries=20 (10.253.6.188) 519.40ms
[E 131210 14:41:56 web:1228] Uncaught exception GET /db?queries=20 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:56 web:1635] 500 GET /db?queries=20 (10.253.6.188) 618.81ms
[E 131210 14:41:57 web:1228] Uncaught exception GET /db?queries=20 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:57 web:1635] 500 GET /db?queries=20 (10.253.6.188) 723.04ms
[E 131210 14:41:58 web:1228] Uncaught exception GET /db?queries=20 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:41:58 web:1635] 500 GET /db?queries=20 (10.253.6.188) 48.53ms
[E 131210 14:42:02 web:1228] Uncaught exception GET /db?queries=20 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:42:02 web:1635] 500 GET /db?queries=20 (10.253.6.188) 731.90ms
[E 131210 14:42:03 web:1228] Uncaught exception GET /db?queries=20 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:42:03 web:1635] 500 GET /db?queries=20 (10.253.6.188) 277.54ms
[E 131210 14:42:06 web:1228] Uncaught exception GET /db?queries=20 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:42:06 web:1635] 500 GET /db?queries=20 (10.253.6.188) 204.13ms
[E 131210 14:42:06 web:1228] Uncaught exception GET /db?queries=20 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:42:06 web:1635] 500 GET /db?queries=20 (10.253.6.188) 520.94ms
[E 131210 14:42:07 web:1228] Uncaught exception GET /db?queries=20 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:42:07 web:1635] 500 GET /db?queries=20 (10.253.6.188) 283.41ms
[E 131210 14:42:08 web:1228] Uncaught exception GET /db?queries=20 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:42:08 web:1635] 500 GET /db?queries=20 (10.253.6.188) 458.50ms
[E 131210 14:42:08 web:1228] Uncaught exception GET /db?queries=20 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:42:08 web:1635] 500 GET /db?queries=20 (10.253.6.188) 159.55ms
[E 131210 14:42:08 web:1228] Uncaught exception GET /db?queries=20 (10.253.6.188)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db?queries=20', version='HTTP/1.1', remote_ip='10.253.6.188', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 53, in get
        world['id'] = world.pop('_id')
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 131210 14:42:08 web:1635] 500 GET /db?queries=20 (10.253.6.188) 57.16ms
